version: "3.0"
services:
  mysql:
    image: 'mysql:8.0.32'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db_data:/var/lib/mysql'

  writting-multiple-destinations:
    image: writting-multiple-destinations
    container_name: writting-multiple-destinations
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  db_data: { }