CREATE TABLE test.CUSTOMER  (
  id BIGINT  NOT NULL PRIMARY KEY ,
  firstName VARCHAR(255) NOT NULL ,
  middleInitial VARCHAR(255),
  lastName VARCHAR(255) NOT NULL,
  address VARCHAR(500) NOT NULL,
  city VARCHAR(125) NOT NULL,
  state CHAR(20) NOT NULL,
  zipCode CHAR(50)
);
