use test;
insert into person values (1, 'foo');
insert into person values (2, 'bar');
insert into person values (3, 'baz');
insert into person values (4, 'Mike');
insert into person values (5, 'Matt');
insert into person values (6, 'Michal');
insert into person values (7, 'Prateek');
insert into person values (8, 'Sagar');
insert into person values (9, 'Sarang');